version: "3"

services:
  ui:
    build:
      context: ./packages/tic-tac-toe-client/
      args:
        - API_URI=${API_URI}
        - WS_URI=${WS_URI}
    ports:
      - "5000:5000"
    expose:
      - 5000
    restart: on-failure
  api:
    build:
      context: ./packages/tic-tac-toe-server
    restart: on-failure
    environment:
      - TYPEORM_HOST=postgres
      - TYPEORM_DATABASE=tictactoe
      - TYPEORM_USERNAME=${POSTGRES_USERNAME}
      - TYPEORM_PASSWORD=${POSTGRES_PASSWORD}
      - TYPEORM_SYNCHRONIZE=false
      - TYPEORM_ENTITIES_DIR=/home/nodejs/app/build/models/**/*.js
      - TYPEORM_MIGRATIONS_DIR=/home/nodejs/app/build/migrations/**/*.js
      - TYPEORM_SUBSCRIBERS_DIR=/home/nodejs/app/build/subscribers/**/*.js
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    expose:
      - 3000
  postgres:
    image: postgres:10.5
    restart: on-failure
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tictactoe
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/include_tictactoe:/etc/nginx/nginx/include_tictactoe
      - ./nginx-local:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - api
      - ui
  backups:
    build:
      context: ./volumerize
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - TZ=Europe/London
      - VOLUMERIZE_SOURCE=/source
      - VOLUMERIZE_JOBBER_TIME=0 0 0 * * *
      - VOLUMERIZE_FULL_IF_OLDER_THAN=7D
      - JOB_NAME2=RemoveOldBackups
      - JOB_TIME2=0 0 1 * * *
      - JOB_COMMAND2=/etc/volumerize/remove-older-than 7D --force
      - VOLUMERIZE_TARGET=${VOLUMERIZE_TARGET}
      - GOOGLE_DRIVE_ID=${GOOGLE_DRIVE_ID}
      - GOOGLE_DRIVE_SECRET=${GOOGLE_DRIVE_SECRET}
      - DATABASE=tictactoe
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - volumerize-cache
      - volumerize-credentials
      - ./source:/source
volumes:
  pg-data:
