version: '3'

services:
  ui:
    environment:
      REACT_APP_API_URI:
        /graphql
    build: ./packages/tic-tac-toe-client
    volumes:
      - public:/home/nodejs/app/build
  api:
    build: ./packages/tic-tac-toe-server
    expose:
     - 3000
  lb:
    image: nginx
    ports:
      - 5000:8080
    volumes:
      - public:/public
      - ./site.conf:/etc/nginx/conf.d/site.conf
volumes:
    public:
