version: "3"

services:
  ui:
    build:
      context: ./packages/tic-tac-toe-client/
      args:
        - API_URI=${API_URI}
        - WS_URI=${WS_URI}
    expose:
      - 5000
  api:
    build: ./packages/tic-tac-toe-server
    environment:
      - MONGO_URI=mongodb://mongo/tictactoe
    depends_on:
      - mongo
    expose:
      - 3000
  mongo:
    image: mongo
