version: "3"

services:
  lb:
    image: nginx
    ports:
      - 8080:8080
    depends_on:
      - api
      - ui
    volumes:
      - ./site.conf:/etc/nginx/conf.d/site.conf
        # command: [nginx-debug, '-g', 'daemon off;']

