version: "3"

services:
  ui:
    build:
      context: ./packages/tic-tac-toe-client/
      args:
        - API_URI=${API_URI}
        - WS_URI=${WS_URI}
    expose:
      - 5000
  api:
    build:
      context: ./packages/tic-tac-toe-server
    environment:
      - TYPEORM_HOST=postgres
      - TYPEORM_DATABASE=tictactoe
      - TYPEORM_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    expose:
      - 3000
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=tictactoe
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
