version: "3"

services:
  lb:
    image: nginx
    ports:
      - 80:8080
    depends_on:
      - api
      - ui
    restart: on-failure
    volumes:
      - ./site.conf:/etc/nginx/conf.d/site.conf
        # command: [nginx-debug, '-g', 'daemon off;']

