version: "3"

services:
  backups:
    image: blacklabelops/volumerize
    restart: unless-stopped
    environment:
        - TZ=Europe/London
        - VOLUMERIZE_SOURCE=/source
        - VOLUMERIZE_JOBBER_TIME=0 0 0 * * *
        - VOLUMERIZE_FULL_IF_OLDER_THAN=7D
        - JOB_NAME2=RemoveOldBackups
        - JOB_COMMAND2=/etc/volumerize/remove-older-than 7D --force
    volumes:
        - /tmp/volumerize_cache:/volumerize-cache
        - ./credentials:/credentials
        - pg-data:/source/pg
  lb:
    image: nginx
    ports:
      - 80:8080
    depends_on:
      - api
      - ui
    restart: on-failure
    volumes:
      - ./site.conf:/etc/nginx/conf.d/site.conf
        # command: [nginx-debug, '-g', 'daemon off;']

