version: "3"

services:
  ui:
    build:
      context: ./packages/tic-tac-toe-client/
      args:
        - API_URI=${API_URI}
        - WS_URI=${WS_URI}
    ports:
      - "5000:5000"
    expose:
      - 5000
  api:
    build:
      context: ./packages/tic-tac-toe-server
    environment:
      - TYPEORM_HOST=postgres
      - TYPEORM_DATABASE=tictactoe
      - TYPEORM_USERNAME=${POSTGRES_USERNAME}
      - TYPEORM_PASSWORD=${POSTGRES_PASSWORD}
      - TYPEORM_SYNCHRONIZE=false
      - TYPEORM_ENTITIES_DIR=/home/nodejs/app/build/models/**/*.js
      - TYPEORM_MIGRATIONS_DIR=/home/nodejs/app/build/migrations/**/*.js
      - TYPEORM_SUBSCRIBERS_DIR=/home/nodejs/app/build/subscribers/**/*.js
    depends_on:
      - postgres
    expose:
      - 3000
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=tictactoe
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
