version: 2
jobs:
  build-ui:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "./packages/tic-tac-toe-client/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          command: yarn
          working_directory: ./packages/tic-tac-toe-client

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "./packages/tic-tac-toe-client/package.json" }}
        
      - run:
          command: yarn build
          working_directory: ./packages/tic-tac-toe-client
  build-server:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "./packages/tic-tac-toe-server/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          command: yarn
          working_directory: ./packages/tic-tac-toe-server

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "./packages/tic-tac-toe-server/package.json" }}

      - run:
          command: yarn build
          working_directory: ./packages/tic-tac-toe-server
  test-ui:
    docker:
      - image: circleci/node:8
    
    working_directory: ~/repo
    
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "./packages/tic-tac-toe-client/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          command: yarn
          working_directory: ./packages/tic-tac-toe-client
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "./packages/tic-tac-toe-client/package.json" }}
      - run:
          command: yarn test
          working_directory: ./packages/tic-tac-toe-client
  deploy-ui:
    docker:
      - image: circleci/node:8
    
    working_directory: ~/repo
    
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "./packages/tic-tac-toe-client/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          command: yarn
          working_directory: ./packages/tic-tac-toe-client
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "./packages/tic-tac-toe-client/package.json" }}
      - run:
          command: yarn build
          working_directory: ./packages/tic-tac-toe-client
      - run:
          command: yarn deploy
          working_directory: ./packages/tic-tac-toe-client
  test-server:
    docker:
      - image: circleci/node:8
    
    working_directory: ~/repo
    
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "./packages/tic-tac-toe-server/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          command: yarn
          working_directory: ./packages/tic-tac-toe-server
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "./packages/tic-tac-toe-server/package.json" }}
      - run:
          command: yarn test
          working_directory: ./packages/tic-tac-toe-server
workflows:
  version: 2
  test:
    jobs:
      - build-ui
      - build-server
      - test-ui:
          requires:
            - build-ui
      - test-server:
          requires:
            - build-server
  deploy:
    - build-ui
    - deploy-ui