version: 2
jobs:
  install-dependencies:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: yarn

      - save_cache:
          paths:
            - node_modules
            - packages/tic-tac-toe-client/node_modules
            - packages/tic-tac-toe-server/node_modules
          key: npm-deps-{{ checksum "./package.json" }}-{{ checksum "./packages/tic-tac-toe-client/package.json" }}-{{ checksum "./packages/tic-tac-toe-server/package.json" }}
  build-ui:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "./package.json" }}-{{ checksum "./packages/tic-tac-toe-client/package.json" }}-{{ checksum "./packages/tic-tac-toe-server/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - npm-deps-

      - run:
          environment:
            API_URI: https://mcr-tictactoe.now.sh/graphql
            PUBLIC_URL: /tic-tac-toe
          command: yarn build
          working_directory: ./packages/tic-tac-toe-client
  build-server:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "./package.json" }}-{{ checksum "./packages/tic-tac-toe-client/package.json" }}-{{ checksum "./packages/tic-tac-toe-server/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - npm-deps-

      - run:
          command: yarn build
          working_directory: ./packages/tic-tac-toe-server
  test-ui:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "./package.json" }}-{{ checksum "./packages/tic-tac-toe-client/package.json" }}-{{ checksum "./packages/tic-tac-toe-server/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - npm-deps-
      - run:
          command: mkdir -p reports/junit
          working_directory: ./packages/tic-tac-toe-client
      - run:
          command: yarn run tslint --format junit -o reports/junit/js-lint-results.xml -p .
          working_directory: ./packages/tic-tac-toe-client
      - run:
          environment:
            JEST_JUNIT_OUTPUT: ./reports/junit/js-test-results.xml
          command: yarn run jest --ci --reporters=default --reporters=jest-junit
          working_directory: ./packages/tic-tac-toe-client
      - run:
          command: bash <(curl -s https://codecov.io/bash)
          working_directory: ./packages/tic-tac-toe-server
      - store_test_results:
          path: ./packages/tic-tac-toe-client/reports/junit
      - store_artifacts:
          path: ./packages/tic-tac-toe-client/reports/junit
  test-server:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "./package.json" }}-{{ checksum "./packages/tic-tac-toe-client/package.json" }}-{{ checksum "./packages/tic-tac-toe-server/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - npm-deps-
      - run:
          command: mkdir -p reports/junit
          working_directory: ./packages/tic-tac-toe-server
      - run:
          command: yarn run tslint --format junit -o reports/junit/js-lint-results.xml -p .
          working_directory: ./packages/tic-tac-toe-server
      - run:
          environment:
            JEST_JUNIT_OUTPUT: ./reports/junit/js-test-results.xml
          command: yarn run jest --ci --reporters=default --reporters=jest-junit
          working_directory: ./packages/tic-tac-toe-server
      - run:
          command: bash <(curl -s https://codecov.io/bash)
          working_directory: ./packages/tic-tac-toe-server
      - store_test_results:
          path: ./packages/tic-tac-toe-server/reports/junit
      - store_artifacts:
          path: ./packages/tic-tac-toe-server/reports/junit
  deploy-ui:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "3e:ef:a8:b3:d8:48:50:fd:c6:61:b9:c7:ec:b3:cb:c9"
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "./package.json" }}-{{ checksum "./packages/tic-tac-toe-client/package.json" }}-{{ checksum "./packages/tic-tac-toe-server/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - npm-deps-
      - run:
          environment:
            API_URI: https://mcr-tictactoe.now.sh/graphql
            PUBLIC_URL: /tic-tac-toe
          command: yarn build
          working_directory: ./packages/tic-tac-toe-client
      - run: git config --global user.email circleci@circleci
      - run: git config --global user.name CircleCI
      - run:
          command: yarn deploy
          working_directory: ./packages/tic-tac-toe-client
  deploy-server:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "./package.json" }}-{{ checksum "./packages/tic-tac-toe-client/package.json" }}-{{ checksum "./packages/tic-tac-toe-server/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - npm-deps-
      - run:
          command: yarn build
          working_directory: ./packages/tic-tac-toe-server
      - run:
          command: npx now -t ${NOW_TOKEN} --regions=bru -e MONGO_URI=@tictactoe_db
          working_directory: ./packages/tic-tac-toe-server
      - run:
          command: npx now -t ${NOW_TOKEN} alias mcr-tictactoe.now.sh
          working_directory: ./packages/tic-tac-toe-server
      - run:
          command: sleep 10 && npx now -t ${NOW_TOKEN} rm tic-tac-toe-server --safe --yes || exit 0
          working_directory: ./packages/tic-tac-toe-server

workflows:
  version: 2
  test:
    jobs:
      - install-dependencies
      - build-ui:
          requires:
            - install-dependencies
          filters:
            branches:
              only: master
      - build-server:
          requires:
            - install-dependencies
          filters:
            branches:
              only: master
      - test-ui:
          requires:
            - build-ui
      - test-server:
          requires:
            - build-server
      - deploy-server:
          requires:
            - test-ui
            - test-server
      - deploy-ui:
          requires:
            - test-ui
            - test-server
